# Generated by Django 4.2.4 on 2023-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_usuario_full_name_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='full_name',
            new_name='nome',
        ),
    ]
